language: node_js
node_js:
  - "6"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database testdb;' -U postgres
script:
  - cd client && npm install && npm test
  - cd ../server && npm install && npm test